### ISSUE TITLE
持续学习

### ISSUE THREAD

**Issue by wonderkun** [huoji120/cpu_duck#1]
我刚还看到这个研究的内容。
https://www.blackhat.com/docs/us-17/thursday/us-17-Domas-Breaking-The-x86-ISA.pdf
感觉可以用来混淆，或者模拟器识别之类的。

**Comment by huoji120** [comment]
如果你感兴趣的话 
https://key08.com/index.php/2022/04/16/1471.html
这是我这几天开始阅读的东西

**Comment by wonderkun** [comment]
@huoji120 嗯，比较感兴趣，持续关注中。
